### ISSUE TITLE
通过 lookout-ext-jvm 上报的jvm相关的metric，能否在tag中添加app名字？

### ISSUE THREAD

**Issue by joker0035** [alipay/sofa-lookout#43]
lookout-ext-jvm 上报的jvm相关的metric的tag只有 instance 和 job， 但是没有spring boot 应用的app， 希望能把这个带过来。 因为在实际业务生产环境中，使用app来对统计数据做聚合和统计都是很有必要的。 
### Environment

- SOFALookout version:  1.5.1
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by joker0035** [comment]
spring boot应用的应用名通常定义在 application.properties中， 
spring.application.name=“xxxxx”

**Comment by khotyn** [comment]
@joker0035 This issue is duplicate with #42 , I'll close this one and will update this issue in  #42 . By the way, we'll support this scenario in the next release.
